docs(deps): update list of peer dependencies #129
AlaskaAirlines/auro-datepicker pull request #130
Opened 2023-06-12 21:00 UTC by jason-capsule42

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #129

## Summary:

Update documented list of peer dependencies

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [ ] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [x] Docs

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2023-06-13 17:43 UTC, blackfalcon commented
You missed the update with the CDN bundles. The reference to design-tokens is incorrect. 

```
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@alaskaairux/design-tokens@latest/dist/tokens/CSSCustomProperties.css" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@aurodesignsystem/webcorestylesheets@latest/dist/bundled/essentials.css" />
<script src="https://cdn.jsdelivr.net/npm/@aurodesignsystem/auro-datepicker@latest/dist/auro-datepicker__bundled.js" type="module"></script>
```

Also, see the screenshot. When using the CDN bundles, it's not appearing as the icons are coming through. 

<img width="1518" alt="Screen Shot 2023-06-13 at 10 41 19 AM" src="https://github.com/AlaskaAirlines/auro-datepicker/assets/181089/6503f4c7-4af9-40db-93fc-78e1e5654c4d">

2023-06-13 17:43 UTC, blackfalcon requested changes

2023-06-13 17:43 UTC, blackfalcon commented on README.md
> +$ npm i alaskaairux/design-tokens
Please update the CDN reference content too.

2023-06-13 19:53 UTC, jason-capsule42 commented
> You missed the update with the CDN bundles. The reference to design-tokens is incorrect.
> 
> ```
> <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@alaskaairux/design-tokens@latest/dist/tokens/CSSCustomProperties.css" />
> <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@aurodesignsystem/webcorestylesheets@latest/dist/bundled/essentials.css" />
> <script src="https://cdn.jsdelivr.net/npm/@aurodesignsystem/auro-datepicker@latest/dist/auro-datepicker__bundled.js" type="module"></script>
> ```
> 
> Also, see the screenshot. When using the CDN bundles, it's not appearing as the icons are coming through.
> 
> <img alt="Screen Shot 2023-06-13 at 10 41 19 AM" width="1518" src="https://user-images.githubusercontent.com/181089/245561345-6503f4c7-4af9-40db-93fc-78e1e5654c4d.png">

They seem to be working for me?

<img width="1800" alt="Screenshot 2023-06-13 at 12 50 47 PM" src="https://github.com/AlaskaAirlines/auro-datepicker/assets/23223137/ddb0563c-2c77-440f-861f-f29ba18a11a4">

2023-06-13 19:55 UTC, blackfalcon approved these changes

2023-06-14 14:56 UTC, merged

2023-06-23 16:38 UTC, blackfalcon commented
:tada: This PR is included in version 2.0.3 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@aurodesignsystem/auro-datepicker/v/2.0.3)
- [GitHub release](https://github.com/AlaskaAirlines/auro-datepicker/releases/tag/v2.0.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: