Add typescript support and change color of calendar cell
AlaskaAirlines/auro-datepicker pull request #132
Opened 2023-06-19 19:50 UTC by jordanjones243

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #118, #125

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

* Add support for typscript users
* Change selected calendar-cell `hover` background color

## Type of change:

Please delete options that are not relevant.

- [x] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2023-06-20 00:39 UTC, jason-capsule42 requested changes

2023-06-20 00:39 UTC, jason-capsule42 commented on README.md
> +<script src="https://cdn.jsdelivr.net/@aurodesignsystem/auro-datepicker@latest/dist/auro-datepicker__bundled.js" type="module"></script>
This needs to be rebuilt using the latest template from WC-Generator. Just rerun the build:docs command.

2023-06-20 20:54 UTC, blackfalcon requested changes

2023-06-20 20:54 UTC, blackfalcon commented on package.json
> +    "typescript": "^5.1.3",
Not a dependency to use. Please move this to devDepedendeincies.

2023-06-28 00:49 UTC, blackfalcon requested changes
When building locally after `npm run sweep` I am getting the following error. 

```
ERROR: ./demo/apiExamples.md file is missing
```

2023-06-28 17:52 UTC, jason-capsule42 approved these changes

2023-06-28 17:53 UTC, merged

2023-06-28 17:58 UTC, blackfalcon commented
:tada: This PR is included in version 2.0.4 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@aurodesignsystem/auro-datepicker/v/2.0.4)
- [GitHub release](https://github.com/AlaskaAirlines/auro-datepicker/releases/tag/v2.0.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: