Jjones/popover issues/#197
AlaskaAirlines/auro-datepicker pull request #204
Opened 2024-03-08 08:36 UTC by jordanjones243

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Resolves:** #197 

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [ ] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [ ] My update follows the CONTRIBUTING guidelines of this project
- [ ] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2024-03-08 18:45 UTC, jason-capsule42 requested changes

2024-03-08 19:27 UTC, blackfalcon requested changes

2024-03-08 19:27 UTC, blackfalcon commented on apiExamples/dynamicSlot.js
> +          populateSlotContentExample.appendChild(slotElement);
nit-pick: please clean up the tabbing.

2024-03-08 20:08 UTC, jordanjones243 commented on src/auro-calendar.js
> +    this.datepicker = this.runtimeUtils.closestElement('auro-datepicker', this);
When moving to the constructor, I get an `undefined` error when trying to call anything in `this.datepicker`. I will leave as is for now.

2024-03-08 20:15 UTC, jordanjones243 commented on src/auro-calendar-cell.js
> +    this.auroPopover.boundary = this.calendarMonth;
Same issue as before. There must be some type of lifecycle issue where the variables are not assigned yet, but are being called in `firstUpdated`

2024-03-12 03:19 UTC, jason-capsule42 approved these changes

2024-03-12 03:20 UTC, merged