Update calendar cell date slot text colors for lowest price highlighting
AlaskaAirlines/auro-datepicker pull request #248
Opened 2024-07-31 23:06 UTC by arrenleung

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Resolves:** #241

## Summary:

Updates the calendar cell date slot text to use `var(--ds-color-text-primary-default` by default and `var(--ds-color-text-success-default` when the slot is used with the `highlight` attribute

![image](https://github.com/user-attachments/assets/51ac985b-6b47-4474-9e8b-4a3fbd1e2cda)

## Type of change:

- [X] New capability
- [X] Revision of an existing capability

## Checklist:

- [X] My update follows the CONTRIBUTING guidelines of this project
- [X] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2024-08-02 18:43 UTC, jordanjones243 requested changes

2024-08-02 18:43 UTC, jordanjones243 commented on src/style-auro-calendar-cell.scss
> +  color: var(--ds-color-text-primary-default, $ds-color-text-primary-default);
Per the design, we need to keep the token we are using for the primary use case of the date slot. Please revert this change. If there were instructions from a different designer, please let me know and I can discuss this with my team!

2024-08-06 16:18 UTC, jordanjones243 commented on src/style-auro-calendar-cell.scss
> +  color: var(--ds-color-text-primary-default, $ds-color-text-primary-default);
The changes to the default color of the date price slot has been approved by designers on the Auro team.

2024-08-06 16:18 UTC, jordanjones243 approved these changes

2024-08-06 16:18 UTC, merged

2024-08-06 21:33 UTC, leeejune commented
Auro design has confirmed changes to the default text color and highlighted text color. Thanks!

2024-08-07 21:54 UTC, blackfalcon commented
:tada: This PR is included in version 2.7.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@aurodesignsystem/auro-datepicker/v/2.7.0)
- [GitHub release](https://github.com/AlaskaAirlines/auro-datepicker/releases/tag/v2.7.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: